apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: statefulset-reader
  namespace: default # Replace with your namespace if not "default"
rules:
  - apiGroups: ["apps"]
    resources: ["statefulsets"]
    verbs: ["get", "list"]
